name: Fetch Update and Publish Release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "4 5 * * *"

env:
  BUILD_TAG: ""
  RELEASE_TAG: ""
  UPDATE_NEEDED: false
  MMKV_REPO_DIR: "./mmkv-repo"
  MMKV_XC_MANIFEST_NAME: MMKV.xcframework.zip

jobs:
  fetch-and-release:
    runs-on: macos-14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.1.1

      - name: Determine Release Tag
        run: |

          wget -O- https://api.github.com/repos/Tencent/MMKV/releases/latest

          echo "-------------------"

          MMKV_TAG=$(wget -q -O- https://api.github.com/repos/Tencent/MMKV/releases/latest | jq -r '.tag_name')
          echo "[*] upstream mmkv tag: $MMKV_TAG"

          # make sure tag is in format v%d.%d.%d
          if [[ ! $MMKV_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "[*] invalid mmkv tag, skip pipeline: $MMKV_TAG"
            exit 1
          fi

          MAJOR_VERSION=$(echo $MMKV_TAG | cut -d'v' -f2 | cut -d'.' -f1)
          MINOR_VERSION=$(echo $MMKV_TAG | cut -d'-' -f2 | cut -d'.' -f2)
          PATCH_VERSION=$(echo $MMKV_TAG | cut -d'-' -f2 | cut -d'.' -f3)
          echo "[*] tag validated, major: $MAJOR_VERSION, minor: $MINOR_VERSION, patch: $PATCH_VERSION"


          BUILD_TAG=$MMKV_TAG
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          RELEASE_TAG="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Check If Compile Required
        run: |
          echo "[*] wants build tag: $RELEASE_TAG"

          git pull --tags
          if git rev-parse "$RELEASE_TAG" >/dev/null 2>&1; then
              echo "[*] tag $RELEASE_TAG already exists, exiting"
              echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          else
              echo "[*] tag $RELEASE_TAG does not exist, building"
              echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Select Xcode
        if: env.UPDATE_NEEDED == 'true'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout MMKV
        if: env.UPDATE_NEEDED == 'true'
        uses: actions/checkout@v4
        with:
          repository: 'Tencent/MMKV'
          ref: ${{ env.BUILD_TAG }}
          path: ${{ env.MMKV_REPO_DIR }}

      - name: Build If Needed
        if: env.UPDATE_NEEDED == 'true'
        run: |

          echo "[*] build tag: $BUILD_TAG"
          echo "[*] release tag: $RELEASE_TAG"

          EST_XCFRAMEWORK_DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/$RELEASE_TAG/$MMKV_XC_MANIFEST_NAME"
          echo "[*] estimated xcframework download url: $EST_XCFRAMEWORK_DOWNLOAD_URL"

          ./scripts/build-mmkv.sh "$BUILD_TAG" "$MMKV_REPO_DIR" "$MMKV_XC_MANIFEST_NAME"
          ./scripts/build-manifest.sh "$MMKV_XC_MANIFEST_NAME" "$EST_XCFRAMEWORK_DOWNLOAD_URL"

      - name: Commit & Push changes
        uses: actions-js/push@master
        if: env.UPDATE_NEEDED == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Make Release
        if: env.UPDATE_NEEDED == 'true'
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body: |
            # Package
            This release was made by automation.
          draft: false
          prerelease: false
          files: ${{ env.MMKV_XC_MANIFEST_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2