name: Fetch Update and Publish Release

on:
  workflow_dispatch:
  schedule:
    - cron: "4 5 * * *"

jobs:
  fetch-and-release:
    runs-on: macos-14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.1.1

      - name: Determine Release Tag
        run: |

          MMKV_TAG=$(wget -q -O- https://api.github.com/repos/Tencent/MMKV/releases/latest | jq -r '.tag_name')
          echo "[*] upstream openssl tag: $MMKV_TAG"

          # make sure tag is in format v-%d.%d.%d
          if [[ ! $MMKV_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "[*] invalid mmkv tag, skip pipeline: $MMKV_TAG"
            exit 0
          fi

          MAJOR_VERSION=$(echo $MMKV_TAG | cut -d'-' -f2 | cut -d'.' -f1)
          MINOR_VERSION=$(echo $MMKV_TAG | cut -d'-' -f2 | cut -d'.' -f2)
          PATCH_VERSION=$(echo $MMKV_TAG | cut -d'-' -f2 | cut -d'.' -f3)
          echo "[*] tag validated, major: $MAJOR_VERSION, minor: $MINOR_VERSION, patch: $PATCH_VERSION"


          BUILD_TAG=$MMKV_TAG
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          RELEASE_TAG="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Check If Compile Required
        run: |
          echo "[*] wants build tag: $BUILD_TAG"

          git pull --tags
          if git rev-parse "$RELEASE_TAG" >/dev/null 2>&1; then
              echo "[*] tag $RELEASE_TAG already exists, exiting"
              echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          else
              echo "[*] tag $RELEASE_TAG does not exist, pass to build"
              echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          fi

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout MMKV
        uses: actions/checkout@v4
        with:
          repository: 'Tencent/MMKV'
          ref: ${{ env.BUILD_TAG }}
          path: "./mmkv-build"

      - name: Build If Needed
        if: env.UPDATE_NEEDED == 'true'
        run: |

          echo "[*] build tag: $BUILD_TAG"
          echo "[*] release tag: $RELEASE_TAG"

          EST_XCFRAMEWORK_DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/$RELEASE_TAG/MMKV.xcframework.zip"
          echo "[*] estimated xcframework download url: $EST_XCFRAMEWORK_DOWNLOAD_URL"

          ./scripts/build-mmkv.sh "$BUILD_TAG"


      - name: Commit & Push changes
        uses: actions-js/push@master
        if: env.UPDATE_NEEDED == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Make Storage Release
        if: env.UPDATE_NEEDED == 'true'
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.STORAGE_RELEASE_TAG }}
          body: |
            # Updated Release
            This release was made by automation.
          draft: false
          prerelease: false
          files: |
            libssl.xcframework.zip

      - name: Make Release
        if: env.UPDATE_NEEDED == 'true'
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body: |
            # Package
            This release was made by automation.
          draft: false
          prerelease: false

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2