# name: release xcframework

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release:
#     runs-on: macos-latest
#     steps:
#       - name: Select Xcode
#         uses: maxim-lobanov/setup-xcode@v1
#         with:
#           xcode-version: latest-stable
#       - name: Get Version
#         run: |
#           echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           repository: 'Tencent/MMKV'
#           ref: ${{ env.VERSION }}
#       - name: Build Binaries
#         run: |
#           rm -rf archives
#           xcodebuild archive \
#           -workspace MMKV.xcworkspace \
#           -scheme MMKV \
#           -configuration Release \
#           -destination "generic/platform=iOS" \
#           -archivePath "archives/MMKV-iOS" \
#           SKIP_INSTALL=NO \
#           BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
#           xcodebuild archive \
#           -workspace MMKV.xcworkspace \
#           -scheme MMKV \
#           -configuration Release \
#           -destination "generic/platform=iOS Simulator" \
#           -archivePath "archives/MMKV-iOS-Simulator" \
#           SKIP_INSTALL=NO \
#           BUILD_LIBRARY_FOR_DISTRIBUTION=YES

#           xcodebuild archive \
#           -workspace MMKV.xcworkspace \
#           -scheme MMKV \
#           -configuration Release \
#           -destination "generic/platform=tvOS" \
#           -archivePath "archives/MMKV-tvOS" \
#           SKIP_INSTALL=NO \
#           BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
#           xcodebuild archive \
#           -workspace MMKV.xcworkspace \
#           -scheme MMKV \
#           -configuration Release \
#           -destination "generic/platform=macOS" \
#           -archivePath "archives/MMKV-macOS" \
#           SKIP_INSTALL=NO \
#           BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
#           xcodebuild \
#           -create-xcframework \
#           -archive archives/MMKV-iOS.xcarchive -framework MMKV.framework \
#           -archive archives/MMKV-iOS-Simulator.xcarchive -framework MMKV.framework \
#           -archive archives/MMKV-tvOS.xcarchive -framework MMKV.framework \
#           -archive archives/MMKV-macOS.xcarchive -framework MMKV.framework \
#           -output archives/MMKV.xcframework
          
#           zip -r -X "archives/MMKV.xcframework.zip" "archives/MMKV.xcframework"
#       - name: Compute Checksum
#         run: |
#           echo "CHECKSUM=$(swift package compute-checksum ./archives/MMKV.xcframework.zip)" >> $GITHUB_ENV
#       - name: Create Release
#         id: create_release
#         uses: ncipollo/release-action@v1
#         with:
#           body: |
#             ```swift
#             let package = Package(
#                 name: "MMKV",
#                 platforms: [
#                     .iOS(.v16),
#                     .macOS(.v13),
#                     .tvOS(.v16),
#                     .visionOS(.v1)
#                 ],
#                 products: [
#                     .library(
#                         name: "MMKV",
#                         targets: ["MMKV"]),
#                 ],
#                 targets: [
#                     .binaryTarget(
#                         name: "MMKV",
#                         url: "https://github.com/AFutureD/mmkv-spm/releases/download/${{ env.VERSION }}/MMKV.xcframework.zip",
#                         checksum: "${{ env.CHECKSUM }}"
#                     )
#                 ]
#             )
#             ```
#           allowUpdates: true
#           artifacts: "archives/MMKV.xcframework.zip"
#           token: ${{ secrets.USER_TOKEN }}
#           tag: ${{ env.VERSION }}
