name: release xcframework

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.3.5)'
        required: true

jobs:
  release:
    runs-on: macos-latest-xlarge
    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'Tencent/MMKV'
          ref: ${{ github.event.inputs.version }}
      - name: Build Binaries
        run: |
          rm -rf archives
          xcodebuild archive \
          -workspace MMKV.xcworkspace \
          -scheme MMKV \
          -configuration Release \
          -destination "generic/platform=iOS" \
          -archivePath "archives/MMKV-iOS" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
          xcodebuild archive \
          -workspace MMKV.xcworkspace \
          -scheme MMKV \
          -configuration Release \
          -destination "generic/platform=iOS Simulator" \
          -archivePath "archives/MMKV-iOS-Simulator" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES

          xcodebuild archive \
          -workspace MMKV.xcworkspace \
          -scheme MMKV \
          -configuration Release \
          -destination "generic/platform=tvOS" \
          -archivePath "archives/MMKV-tvOS" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
          xcodebuild archive \
          -workspace MMKV.xcworkspace \
          -scheme MMKV \
          -configuration Release \
          -destination "generic/platform=macOS" \
          -archivePath "archives/MMKV-macOS" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
          xcodebuild \
          -create-xcframework \
          -archive archives/MMKV-iOS.xcarchive -framework MMKV.framework \
          -archive archives/MMKV-iOS-Simulator.xcarchive -framework MMKV.framework \
          -archive archives/MMKV-tvOS.xcarchive -framework MMKV.framework \
          -archive archives/MMKV-macOS.xcarchive -framework MMKV.framework \
          -output archives/MMKV.xcframework
          
          zip -r -X "archives/MMKV.xcframework.zip" "archives/MMKV.xcframework"
      - name: Compute Checksum
        id: checksum
        run: |
          echo "checksum=$(swift package compute-checksum ./archives/MMKV.xcframework.zip)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          body: |
            ```swift
            .binaryTarget(
                name: "MMKV",
                url: "https://github.com/devjia/mmkv-spm/releases/download/${{ github.event.inputs.version }}/MMKV.xcframework.zip",
                checksum: "${{ steps.checksum.outputs.checksum }}"
            ),
            ```
          allowUpdates: true
          artifacts: "archives/MMKV.xcframework.zip"
          token: ${{ secrets.USER_TOKEN }}
          tag: ${{ github.event.inputs.version }}
